### ISSUE TITLE
No arrays? No loops?

### ISSUE THREAD

**Issue by fzxt** [patrickdes96/ArrayLoop#1]
There is no code.

Where are the arrays? Where are said loops?

Best
-- Fahad

**Comment by ilaskaev** [comment]
Please add a readme

**Comment by justcarthy** [comment]
how do i install this on my machines: my specs are:

OS: Ubuntu 16.10 x86_64 
Model: 20266 Lenovo Yoga 2 Pro 
Kernel: Linux 4.8.0-38-generic 
Uptime: 18 hours, 45 minutes 
Packages: 3160 
Shell: bash 4.3.46 
Resolution: 3200x1800 
WM: i3 
Theme: Arc [GTK3] 
Icons: Lüv Dark [GTK3] 
Terminal: urxvt
CPU: Intel i7-4500U (4) @ 3.0GHz [82.0°C] 
GPU: Intel Haswell Mobile 
Memory: 1412MiB / 7895MiB 
Disk (/): 63G / 89G (75%) 
Local IP: Screw.you.hacker.police 
Birthday: Tue 05 Apr 2016 1:46 PM 

Thank you.

**Comment by yinny** [comment]
Can I use this in my project its for school i will credit

**Comment by yinny** [comment]
respond pls??

**Comment by patrickdes96** [comment]
This is proprietary software. Any attempt to access will be issued a notice from the Legend
