### ISSUE TITLE
fork permission

### ISSUE THREAD

**Issue by baala108** [patrickdes96/ArrayLoop#2]

**Comment by fzxt** [comment]
+1. This repo isn't meeting the needs of most developers these days.

**Comment by justcarthy** [comment]
unstarred. please support the [`community`](https://github.com/lhartikk/ArnoldC/blob/c434fe95137e8cd7b787db7a1fdc5be3982cb668/src/test/scala/org/arnoldc/MethodTest.scala#L9)

**Comment by patrickdes96** [comment]
This is proprietary software. Please refrain from accessing. Thank you
